### ISSUE TITLE
Modded banner patterns don't work

### ISSUE THREAD

**Issue by yuvalyly** [uecasm/colony4cc#15]
When this mod is installed, modded banner patterns no longer work as a colony banner (or at least the patterns from Ice and Fire, that is the only mod I have installed that adds patterns). The patterns still appear on the list but they all just a line at the bottom
![2022-04-11_23 33 49](https://user-images.githubusercontent.com/40964623/162832311-f0a813c1-d594-4cf1-ad23-ed7fbea6c024.png)
.

**Comment by uecasm** [comment]
That doesn't make much sense to me, because this mod doesn't touch anything related to banners (or indeed anything in the GUI at all).

What versions of Minecolonies and colony4cc are you using?  Are you absolutely sure that removing colony4cc with no other changes causes the problem and it comes back when you re-add it?

**Comment by yuvalyly** [comment]
Yes, I double checked it, the problem only happens when colony4cc is installed, and it's not just the GUI, the colony banner is also broken when placed when using modded patterns, and I just discovered that it's not just the colony banner, but any banner that uses a modded pattern. I'm using minecolonies-1.16.5-1.0.429-RELEASE and Colony4ComputerCraft-1.16.5-1.4.1
![2022-04-12_10 02 06](https://user-images.githubusercontent.com/40964623/162900585-ab8114ac-882e-4a11-8ecd-6b6a429e469d.png)
![2022-04-12_10 02 27](https://user-images.githubusercontent.com/40964623/162900602-6d4e34fd-e729-4bfa-90bd-49b07ca1a012.png)

.

**Comment by uecasm** [comment]
This should now be fixed in 1.18+.
