### ISSUE TITLE
Server Crashes when putting in prompts getWorkOrders() & getBuilding()

### ISSUE THREAD

**Issue by LionoftheWest** [uecasm/colony4cc#17]
My buddy and I run a modded server running ATM7 0.3.18 with the Minecolonies 1.18.2-1.0.636-BETA and we wanted to use the integrator to get all the minecolony we've built to be automated and easier to manage. However every time we've put in the codes it entirely crashes the server, and we also tried it for a couple other codes. Not sure whats going on and there doesn't seem to be any other issues so far here that I've seen like it

**Comment by uecasm** [comment]
Due to some breaking changes on the MineColonies side, it's not currently compatible with versions > 550 or so.  I have some updates in the works but they're not released yet.  Soon™.

Having said that, if you want to report crashing problems then please fill in the template properly and include versions and logs.

**Comment by uecasm** [comment]
Ok, there should (in a few minutes) be some 1.18.2 releases of colony4cc available, which should fix this.  Or if not, please include logs next time.
