### ISSUE TITLE
getPlayers gives NullPointerException

### ISSUE THREAD

**Issue by RedStoner** [uecasm/colony4cc#9]
Getting a null pointer just by running colony.getPlayers()

![image](https://user-images.githubusercontent.com/1278466/134489751-3d12083e-a3a4-49d2-ab08-f302d8609dac.png)
 
versions -
Colony4ComputerCraft-1.16.5-1.4.0
cc-tweaked-1.16.5-1.98.2
minecolonies-1.0.0-RELEASE-universal
structurize-0.13.219-ALPHA-universal

**Comment by uecasm** [comment]
Hmm.  I don't get any errors with those versions in my test world.  It must be something specific to your particular colony.

I'll need to see the server log files.  Or alternatively you can try doing an /mc colony export N and send me the backup file that it generates so that I can try to reproduce it with your colony data.

**Comment by RedStoner** [comment]
Hmm, you are correct, it is only my colony..... I can run the command on others in the server..  Server host is not around at the moment. will upload a log and backup file as soon as i have access too them. While I wait though, any thoughts on what in my colony could be doing this?

**Comment by RedStoner** [comment]
[colony3Export.zip](https://github.com/uecasm/colony4cc/files/7221284/colony3Export.zip)
Found another colony on the server where this errors in the same way...

**Comment by uecasm** [comment]
Thanks, I've looked into this export and it looks like sort-of a bug in MineColonies, but I can't work out how to get it into the bad state starting from the current version.  So possibly it was a bug in a previous version that has since been fixed, but your colony still contains some bad data.  (Or possibly there's some special condition to trigger it that I haven't discovered.)

The good news is that you can "fix" your existing colonies fairly easily -- go to the Permissions page and delete the "auto" custom rank (the option to delete ranks shows up if you click "settings" on the right side -- very well hidden!).  It's ok to create it again afterwards if you like (it seems to create correctly in this version), but something about that particular rank didn't get set up correctly inside the colony data and it's what is causing that error.

Your other colony is probably the same thing; just perhaps a different custom rank to delete.

Please share any other details on how to cause the bad state (if you can think of something) or anything else of relevance in the linked issue.

**Comment by RedStoner** [comment]
Well. That is wonderfull news. Thank you for this. I appreciate.
